version: "3.7"
services:

  # Snapshot hub
  snapshot-hub:
    build: .
    container_name: snapshot-hub
    env_file:
      - .env.local
    environment:
      PORT: 8080
      JAWSDB_URL: postgres://admin:admin@snapshot-postgres:5432/snapshot
    depends_on:
      - snapshot-postgres
    ports:
      - "8080:8080"

  # Snapshot Postgres instance
  snapshot-postgres:
    image: postgres:12.2-alpine
    container_name: snapshot-postgres
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "snapshot"
    volumes:
        - ./server/helpers/database/:/docker-entrypoint-initdb.d

networks:
  default:
    name: snapshot-network
